global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  -  job_name: 'prometheus' # Job to scrape Prometheus metrics
     scrape_interval: 5s
     static_configs:
       - targets: ['localhost:9090']
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus' # Job to scrape application
    scrape_interval: 5s
    static_configs:
      - targets: ['demoapp:8081']
        labels:
          application: 'My Spring Boot Application'
