version: '3'

services:
  demoapp:
    container_name: order_service
    image: order_management
    build: ..
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - database
  database:
    container_name: order_db
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    volumes:
      - ./infrastructure/db.sql:/docker-entrypoint-initdb.d/db.sql
      - order-data:/var/lib/postgresql/data #persist data even if container shuts down
  pgadmin:
    # UI is available at http://localhost:5050/browser/, server connection params are hostname: postgres-order, port: 5432 and use above database credentials
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
    ports:
      - '5050:80'
  prometheus:
    image: prom/prometheus
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ../monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

volumes:
  order-data: # named volumes can be managed easier using docker-compose